name: task_management_app
description: " Task Management & To-Do List app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  dio: ^5.4.0
  get_it: ^7.7.0
  go_router: ^13.2.0
  equatable: ^2.0.5
  gap: ^3.0.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/